# Homebrew Formula for hoot
# This is auto-generated by GoReleaser. Manual installation:

class Hoot < Formula
  desc "A Nostr CLI client with TUI support"
  homepage "https://github.com/oth-body/hoot"
  version "0.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/oth-body/hoot/releases/download/v#{version}/hoot-darwin-amd64.tar.gz"
      sha256 "" # Updated by GoReleaser
    end
    on_arm do
      url "https://github.com/oth-body/hoot/releases/download/v#{version}/hoot-darwin-arm64.tar.gz"
      sha256 "" # Updated by GoReleaser
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oth-body/hoot/releases/download/v#{version}/hoot-linux-amd64.tar.gz"
      sha256 "" # Updated by GoReleaser
    end
    on_arm do
      url "https://github.com/oth-body/hoot/releases/download/v#{version}/hoot-linux-arm64.tar.gz"
      sha256 "" # Updated by GoReleaser
    end
  end

  def install
    bin.install "hoot"
    etc.install "relays.txt.example" => "hoot/relays.txt.example" if File.exist?("relays.txt.example")
  end

  test do
    assert_match "nostr-cli version", shell_output("#{bin}/hoot -version")
  end
end
